version: '3.3'
services:
  mindesk:
    build: '.'
    ports:
      - '8080:8080'
    depends_on:
      - 'mongodb'
    networks:
      - mongo-go
  mongodb:
    image: 'mongo'
    container_name: 'mongodb'
    ports:
      - '27017:27017'
    volumes:
    - 'mongodata:/data/db'
    networks:
      - mongo-go
volumes:
  mongodata:

networks:
  mongo-go: