name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: |
        cd cmd/mindesk
        go build -v mindesk-app
      
    - name: Start MongoDB
      # You may pin to the exact commit or the version.
      # uses: supercharge/mongodb-github-action@310bd1bbeb878d9de3e54ee492cbd9643b1e8875
      uses: supercharge/mongodb-github-action@1.3.0
      # with:
        # MongoDB version to use (default "latest")
        # mongodb-version: # optional, default is latest
        # MongoDB replica set name (no replica set by default)
        # mongodb-replica-set: # optional, default is 
    
    - name: Test models
      run: go test -v min-desk-backend/test/models
